# todo: https://docs.docker.com/compose/networking/
version: "3.9"
services:
  porcupine-go:
    build: "./main"
    ports:
      - "8080"
  porcupine-rs:
    build: "./main"
    ports:
      - "5000"
  porcupine-erl:
    build: "./main"
    ports:
      - "4000"
