name: Go
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: build
        uses: actions/setup-go@v4
        with:
          go-version: '1.21.x'
      
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build -v -race ./...
      - name: Run vetting
        run: go vet

  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: test
      uses: actions/setup-go@v4
      with:
        go-version: '1.21.x'

    - name: Install dependencies
      run: go mod download

    - name: Test with the Go CLI
      run: go test -v -race ./...

    - name: Run BenchMarks
      run: cd porcupine && go test -bench=. -benchmem ./...

    - name: Run tests with coverage
      id: go-test
      run: go test -coverprofile=coverage.out ./...
    
    - name: Display coverage
      run: go tool cover -func=coverage.out
    
    - name: threshold
      run: |
        THRESHOLD=70.0
        COVERAGE=$(go tool cover -func=coverage.out | grep '^pkg/' | awk '{sum+=$3; count+=1} END {if (count > 0) print sum/count; else print 0}')
        if (( $(echo "$COVERAGE < $THRESHOLD" | bc -l) )); then
          echo "Code coverage ($COVERAGE%) is below the threshold ($THRESHOLD%) for /pkg"
          exit 1
        fi
