name: Go
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.x'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v -race ./...
      - name: Test with the Go CLI
        run: go test -v -race ./...
      - name: Run vetting
        run: go vet
      - name: Run BenchMarks
        run: cd porcupine && go test -bench=. -benchmem ./...
